version: '3.8'
services:
  postgres:
    image: "postgres:13.1-alpine" # FIXME, add version.
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/opt/jboss/keycloak/realm-config/lunatech-realm.json"
    volumes:
      - ./infra/keycloak:/opt/jboss/keycloak/realm-config
    ports:
      - 8762:8080



# Uncomment and run this service to generate an export of keycloak.
#  keycloak-exporter:
#    image: quay.io/keycloak/keycloak:11.0.3
#    container_name: keycloak-exporter
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: postgres
#      DB_PORT: 5432
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: keycloak
#    volumes:
#      - ./keycloak-export:/tmp/keycloak-export
#    command: -Dkeycloak.migration.action=export\
#             -Dkeycloak.migration.provider=singleFile\
#             -Dkeycloak.migration.file=/tmp/keycloak-export/keycloak-export.json\
#             -Dkeycloak.migration.realmName=lunatech
