version: '3.8'
services:
  postgres:
    image: "postgres:13.1-alpine" # FIXME, add version.
    container_name: quarkus-course-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  zookeeper:
    image: quay.io/strimzi/kafka:0.21.1-kafka-2.7.0
    container_name: quarkus-course-zk
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.21.1-kafka-2.7.0
    container_name: quarkus-course-kafka
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: quarkus-course-keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/opt/jboss/keycloak/realm-config/lunatech-realm.json"
    volumes:
      - ./infra/keycloak:/opt/jboss/keycloak/realm-config
    ports:
      - 8762:8080



# Uncomment and run this service to generate an export of keycloak.
#  keycloak-exporter:
#    image: quay.io/keycloak/keycloak:11.0.3
#    container_name: keycloak-exporter
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: postgres
#      DB_PORT: 5432
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: keycloak
#    volumes:
#      - ./keycloak-export:/tmp/keycloak-export
#    command: -Dkeycloak.migration.action=export\
#             -Dkeycloak.migration.provider=singleFile\
#             -Dkeycloak.migration.file=/tmp/keycloak-export/keycloak-export.json\
#             -Dkeycloak.migration.realmName=lunatech
